"""add_tenant_id_to_conversations

Revision ID: 14e1dfdf2a5b
Revises: 8c6d18516e08
Create Date: 2026-03-19 22:27:08.207462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14e1dfdf2a5b'
down_revision: Union[str, Sequence[str], None] = '8c6d18516e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('messages', sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'citations')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'tenant_id')
    # ### end Alembic commands ###
