'use client';

import React, { useState, useEffect } from 'react';
import { Receipt, Clock, Loader2, ArrowUpRight, TrendingUp } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { toast } from 'sonner';

interface Invoice {
  id: string;
  amount: number;
  status: string;
  created_at: string;
  due_date?: string;
}

export default function FinancePage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchInvoices = async () => {
    try {
      const res = await apiFetch('/v1/invoices');
      if (res.ok) {
        const data = await res.json();
        setInvoices(data);
      }
    } catch (err) {
      console.error('Failed to fetch invoices:', err);
      toast.error('Failed to load finance data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInvoices();
  }, []);

  const totalRevenue = invoices
    .filter(inv => inv.status === 'paid')
    .reduce((sum, inv) => sum + (inv.amount || 0), 0);

  const pendingRevenue = invoices
    .filter(inv => inv.status === 'sent' || inv.status === 'pending')
    .reduce((sum, inv) => sum + (inv.amount || 0), 0);

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 text-primary">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2 text-primary">Finance</h1>
          <p className="text-secondary">Manage billings, invoices, and revenue tracking.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-surface border border-dim rounded-xl p-6 shadow-sm hover:border-accent/40 transition-all group">
          <div className="flex justify-between items-start mb-4">
            <div className="p-2.5 rounded-lg bg-green-status/10 text-green-status group-hover:scale-110 transition-transform">
              <TrendingUp size={24} />
            </div>
            <div className="text-[10px] font-bold text-green-status bg-green-status/10 px-2 py-1 rounded flex items-center gap-1">
              +12.5% <ArrowUpRight size={10} />
            </div>
          </div>
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted mb-1">Total Revenue</div>
          <div className="text-2xl font-bold text-primary">${totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
        </div>

        <div className="bg-surface border border-dim rounded-xl p-6 shadow-sm hover:border-accent/40 transition-all group">
          <div className="flex justify-between items-start mb-4">
            <div className="p-2.5 rounded-lg bg-accent/10 text-accent group-hover:scale-110 transition-transform">
              <Clock size={24} />
            </div>
          </div>
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted mb-1">Pending Invoices</div>
          <div className="text-2xl font-bold text-primary">${pendingRevenue.toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
        </div>

        <div className="bg-surface border border-dim rounded-xl p-6 shadow-sm hover:border-accent/40 transition-all group">
          <div className="flex justify-between items-start mb-4">
            <div className="p-2.5 rounded-lg bg-muted/10 text-muted group-hover:scale-110 transition-transform">
              <Receipt size={24} />
            </div>
          </div>
          <div className="text-[11px] font-bold uppercase tracking-widest text-muted mb-1">Total Invoices</div>
          <div className="text-2xl font-bold text-primary">{invoices.length}</div>
        </div>
      </div>

      {loading ? (
        <div className="h-64 flex items-center justify-center bg-surface border border-dim rounded-xl">
          <Loader2 className="animate-spin h-8 w-8 text-accent" />
        </div>
      ) : invoices.length === 0 ? (
        <div className="border border-dim rounded-xl p-12 text-center bg-surface flex flex-col items-center">
          <div className="w-16 h-16 bg-muted/10 rounded-full flex items-center justify-center mb-4">
            <Receipt className="h-8 w-8 text-muted opacity-40" />
          </div>
          <h3 className="text-lg font-medium text-primary">No invoices found</h3>
          <p className="text-secondary mt-2 max-w-xs mx-auto">Invoices will be generated by the Finance Agent automatically upon milestone completion.</p>
        </div>
      ) : (
        <div className="border border-dim rounded-xl bg-surface overflow-hidden shadow-sm">
          <div className="p-4 border-b border-dim bg-elevated/20">
            <h3 className="text-[12px] font-bold text-muted uppercase tracking-wider">Recent Invoices</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-dim bg-elevated/10">
                  <th className="px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-muted">Reference</th>
                  <th className="px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-muted">Status</th>
                  <th className="px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-muted">Amount</th>
                  <th className="px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-muted">Due Date</th>
                  <th className="px-6 py-4 text-[10px] font-bold uppercase tracking-widest text-muted text-right">Created</th>
                </tr>
              </thead>
              <tbody>
                {invoices.map((invoice) => (
                  <tr key={invoice.id} className="border-b border-dim hover:bg-elevated/20 transition-colors group">
                    <td className="px-6 py-4">
                      <div className="font-mono text-[12px] text-accent p-1 bg-accent/5 rounded inline-block">
                        #{invoice.id.split('-')[0].toUpperCase()}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`text-[9px] font-bold uppercase tracking-widest px-2.5 py-1 rounded-full border ${
                        invoice.status === 'paid' ? 'bg-green-status/10 text-green-status border-green-status/20' : 
                        invoice.status === 'sent' || invoice.status === 'pending' ? 'bg-accent/10 text-accent border-accent/20' : 
                        'bg-muted/10 text-muted border-muted/20'
                      }`}>
                        {invoice.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 font-bold text-primary text-sm">${invoice.amount.toFixed(2)}</td>
                    <td className="px-6 py-4 text-sm text-secondary">
                      <div className="flex items-center gap-1.5">
                        <Calendar size={12} className="text-muted" />
                        {invoice.due_date ? new Date(invoice.due_date).toLocaleDateString() : '—'}
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-muted text-right">
                      {new Date(invoice.created_at).toLocaleDateString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}

const Calendar = ({ size, className }: { size: number, className?: string }) => (
  <svg 
    width={size} 
    height={size} 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="2" 
    strokeLinecap="round" 
    strokeLinejoin="round" 
    className={className}
  >
    <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
    <line x1="16" y1="2" x2="16" y2="6"></line>
    <line x1="8" y1="2" x2="8" y2="6"></line>
    <line x1="3" y1="10" x2="21" y2="10"></line>
  </svg>
);
